appname = egresados_crud
httpport = ${EGRESADOS_CRUD_HTTPPORT||8080}
runmode = ${EGRESADOS_CRUD_RUNMODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}
PGuser = ${EGRESADOS_CRUD_DB_USER}
PGpass = ${EGRESADOS_CRUD_DB_PASS}
PGhost = ${EGRESADOS_CRUD_DB_URL}
PGport = ${EGRESADOS_CRUD_DB_PORT}
PGdb   = ${EGRESADOS_CRUD_DB_NAME}
PGschema = ${EGRESADOS_CRUD_DB_SCHEMA}


#appname = egresados_crud
#httpport = 8080
#runmode = dev
#autorender = false
#copyrequestbody = true
#EnableDocs = true
#
#PGuser = postgres
#PGpass =
#PGhost = 127.0.0.1
#PGdb   = beneficios_egresados
#PGschema = beneficios_egresados
#PGport = 5432
