appname = egresados_crud
httpport = ${EGRESADOS_CRUD_HTTP_PORT||8080}
runmode = ${EGRESADOS_CRUD_RUN_MODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}
PGuser = ${EGRESADOS_CRUD_PGUSER}
PGpass = ${EGRESADOS_CRUD_PGPASS}
PGhost = ${EGRESADOS_CRUD_PGHOST}
PGport = ${EGRESADOS_CRUD_PGPORT}
PGdb   = ${EGRESADOS_CRUD_PGDB}
PGschema = ${EGRESADOS_CRUD_PGSCHEMA}


#appname = egresados_crud
#httpport = 8080
#runmode = dev
#autorender = false
#copyrequestbody = true
#EnableDocs = true
#
#PGuser = postgres
#PGpass =
#PGhost = 127.0.0.1
#PGdb   = beneficios_egresados
#PGschema = beneficios_egresados
#PGport = 5432
